In [ ]:
pip install transformers

     |████████████████████████████████| 2.5MB 4.0MB/s 
     |████████████████████████████████| 3.3MB 18.7MB/s 
     |████████████████████████████████| 901kB 34.8MB/s 


In [ ]:
from transformers import pipeline
classifier = pipeline('sentiment-analysis')

In [ ]:
classifier('i am feeling very tired')

[{'label': 'NEGATIVE', 'score': 0.9997531175613403}]

In [ ]:
sent = classifier(["I am a ambitious girl", "I will follow my dreams to achieve it"])
sent

[{'label': 'POSITIVE', 'score': 0.9996944665908813},
 {'label': 'POSITIVE', 'score': 0.9997865557670593}]

In [ ]:
classifier = pipeline('sentiment-analysis', model = "nlptown/bert-base-multilingual-uncased-sentiment")

In [ ]:
classifier("Je suis très triste à cause du mauvais incident qui s'est produit récemment.")

[{'label': '1 star', 'score': 0.46887069940567017}]

In [ ]:
# Using AutoTokenizer and Pretrained model
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

In [ ]:
model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
model = TFAutoModelForSequenceClassification.from_pretrained(model_name, from_pt = True)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

All the weights of TFBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [ ]:
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [ ]:
classifier = pipeline('sentiment-analysis', model = model_name, tokenizer= tokenizer)

In [ ]:
classifier("Je suis très triste à cause du mauvais incident qui s'est produit récemment.")

[{'label': '1 star', 'score': 0.46887069940567017}]

In [ ]:
tf_batch = tokenizer(['I am very tired', 'I am very soo sweet'], padding = True, truncation = True, max_length = 512, return_tensors= 'tf') 

In [ ]:
tf_batch

{'input_ids': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[  101,   151, 10345, 12495, 35235, 10163,   102],
       [  101,   151, 10345, 12495, 41667, 19355,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}